import {
    VideoCamera,
    Film,
    Lollipop,
    Camera,
    Service,
    ShoppingBag,
    Document as IconDocument,
    Menu as IocnMenu,
    Picture
} from "@element-plus/icons-vue";

export default {
    bgrj: { name: "办公软件", icon: ShoppingBag, color: "#15AABF" },
    bz: { name: "图片", icon: Picture, color: "#FED43C" },
    cbs: { name: "出版", icon: IconDocument, color: "#4C6EF5" },
    fj: { name: "壁纸", icon: Picture, color: "#FED43C" },
    hydm: { name: "动漫", icon: Lollipop, color: "#9CCA49" },
    hyds: { name: "电视", icon: VideoCamera, color: "#FED43C" },
    hydy: { name: "电影", icon: Film, color: "#EE3525" },
    hyyy: { name: "音乐", icon: Service, color: "#FD7E13" },
    jlp: { name: "视频", icon: Camera, color: "#4DABF7" },
    jypx: { name: "视频", icon: Camera, color: "#4DABF7" },
    kfrj: { name: "软件", icon: ShoppingBag, color: "#15AABF" },
    mh: { name: "文档", icon: IconDocument, color: "#4C6EF5" },
    omdm: { name: "欧美动漫", icon: Lollipop, color: "#9CCA49" },
    omds: { name: "欧美电视", icon: VideoCamera, color: "#FED43C" },
    omdy: { name: "欧美电影", icon: Film, color: "#EE3525" },
    omyy: { name: "欧美音乐", icon: Service, color: "#FD7E13" },
    qt: { name: "其他", icon: IocnMenu, color: "#E8ECF3" },
    qtds: { name: "其他电视", icon: IocnMenu, color: "#E8ECF3" },
    qtdy: { name: "其他电影", icon: IocnMenu, color: "#E8ECF3" },
    qtrj: { name: "其他软件", icon: IocnMenu, color: "#E8ECF3" },
    qtsp: { name: "其他", icon: IocnMenu, color: "#E8ECF3" },
    qttp: { name: "其他", icon: IocnMenu, color: "#E8ECF3" },
    qtwd: { name: "其他", icon: IocnMenu, color: "#E8ECF3" },
    qtyy: { name: "其他音乐", icon: IocnMenu, color: "#E8ECF3" },
    rbdm: { name: "日本动漫", icon: Lollipop, color: "#9CCA49" },
    rhdm: { name: "日韩动漫", icon: Lollipop, color: "#9CCA49" },
    rhds: { name: "日韩电视", icon: VideoCamera, color: "#FED43C" },
    rhdy: { name: "日韩电影", icon: Film, color: "#EE3525" },
    rhyy: { name: "日韩音乐", icon: Service, color: "#FD7E13" },
    rw: { name: "图片", icon: Picture, color: "#FED43C" },
    wlrj: { name: "软件", icon: ShoppingBag, color: "#15AABF" },
    xs: { name: "小说", icon: IconDocument, color: "#4C6EF5" },
    xtrj: { name: "系统软件", icon: ShoppingBag, color: "#15AABF" },
    zspx: { name: "知识", icon: IconDocument, color: "#4C6EF5" },
    zyp: { name: "综艺", icon: Camera, color: "#4DABF7" },
}
